// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kipqzmgjqwijpulxctfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcHF6bWdqcXdpanB1bHhjdGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDQ5NjEsImV4cCI6MjA1NTU4MDk2MX0.ZABOxK3HcCHlDfsmMb4roR9cC6AeGlMpJAdYu2_dADs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);